# Input file path
input.path=data/raw_bookings.csv

# Output file paths
output.cleaned=output/cleaned.csv
output.rejected=output/rejected.csv
output.aggregation=output/aggregation.csv

# Database Configuration
# db.enabled=true
#db.url=jdbc:mysql://localhost:3306/busdb
#db.username=root
#db.password=231814

db.enabled=true

db.url=jdbc:mysql://root:hwfZSIgVUzOqYxOpUMswcPaLmuyjWpNr@shuttle.proxy.rlwy.net:47109/railway
db.username=root
db.password=hwfZSIgVUzoqYxOpUMswcPalMuyjWpNr